--- ./Makefile
+++ ./Makefile
@@ -4,7 +4,7 @@
 
 ### Environment constants 
 
-LGW_PATH ?= ../../lora_gateway/libloragw
+LGW_PATH ?= ../../../../lora-gateway/5.0.1-r0/git/libloragw
 ARCH ?=
 CROSS_COMPILE ?=